#User Configuration

#OE_TERMINAL = "tmux"




MACHINE_FEATURES:append = " fpga-overlay"
BB_SERVER_TIMEOUT = "600"
BB_NUMBER_THREADS = "6"
PARALLEL_MAKE = "-j 6"
RM_WORK_EXCLUDE += "xrt"

IMAGE_INSTALL:append = " xrt"
IMAGE_INSTALL:append = " wilc wilc3000-fw ultra96-ap-setup ultra96-wpa"

