#User Configuration

#OE_TERMINAL = "tmux"


PREMIRRORS:prepend = "git://.*/.* file:///home/albertabeef/petalinux_cache/downloads_2024.2/ \ 
 ftp://.*/.* file:///home/albertabeef/petalinux_cache/downloads_2024.2/ \ 
 http://.*/.* file:///home/albertabeef/petalinux_cache/downloads_2024.2/ \ 
 https://.*/.* file:///home/albertabeef/petalinux_cache/downloads_2024.2/ "

DL_DIR = "/home/albertabeef/petalinux_cache/downloads_20234.2/"
SSTATE_DIR = "/home/albertabeef/petalinux_cache/sstate_2024.2/aarch64/"
IMAGE_BOOT_FILES:versal = "BOOT.BIN boot.scr Image  system.dtb"
